version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_database_user
      POSTGRES_PASSWORD: my_database_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U my_database_user -d my_database -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 1
  web:
    build: .
    command: gunicorn KhedmatkarBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "28301:8000"
    depends_on:
#      - db
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./404.html:/usr/share/nginx/html/404.html
    ports:
      - "80:80"
    depends_on:
      - web