# Generated by Django 4.2.7 on 2023-11-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('reception_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('FINDING_SPECIALIST', 'Finding Specialist'), ('WAITING_FOR_SPECIALIST_ACCEPTANCE', 'Waiting for Specialist Acceptance'), ('WAITING_FOR_CUSTOMER_ACCEPTANCE', 'Waiting for Customer Acceptance'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='FINDING_SPECIALIST', max_length=50)),
                ('geo_point', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING_FOR_SPECIALIST_ACCEPTANCE', 'Waiting For Specialist Acceptance'), ('REJECTED_BY_SPECIALIST', 'Rejected By Specialist'), ('WAITING_FOR_CUSTOMER_ACCEPTANCE', 'Waiting For Customer Acceptance'), ('REJECTED_BY_CUSTOMER', 'Rejected By Customer'), ('ACCEPTED', 'Accepted')], max_length=50)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
        ),
    ]
