from django.db import models


class ServiceRequestSpecialistStatus(models.TextChoices):
    WAITING_FOR_SPECIALIST_ACCEPTANCE = 'WAITING_FOR_SPECIALIST_ACCEPTANCE'
    REJECTED_BY_SPECIALIST = 'REJECTED_BY_SPECIALIST'
    WAITING_FOR_CUSTOMER_ACCEPTANCE = 'WAITING_FOR_CUSTOMER_ACCEPTANCE'
    REJECTED_BY_CUSTOMER = 'REJECTED_BY_CUSTOMER'
    ACCEPTED = 'ACCEPTED'
